[package]
name = "phantasm"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.22"

#[dependencies.malachite]
#version = "0.4.2"